from fastapi import APIRouter
from app.api.v1.endpoints import auth, workos_lifecycle, customers, vehicles, repair_orders, inventory, dashboard, services, appointments, payments, mechanics, suppliers, quotes, invoices, stripe_connect, stripe_webhooks, quickbooks, google_reviews, admin, platform_payments, websocket, invoice_access, messages, twilio_webhooks, fleet, driver_accountability, labor_book_time, activity, reports, conversion_exports, parts_operations, inventory_lifecycle

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(workos_lifecycle.router, prefix="/auth/workos", tags=["workos"])
api_router.include_router(websocket.router, tags=["websocket"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(platform_payments.router, prefix="/admin/payments-control", tags=["platform-payments"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(vehicles.router, prefix="/vehicles", tags=["vehicles"])
api_router.include_router(repair_orders.router, prefix="/repair-orders", tags=["repair-orders"])
api_router.include_router(quotes.router, prefix="/quotes", tags=["quotes"])
api_router.include_router(invoices.router, prefix="/invoices", tags=["invoices"])
api_router.include_router(invoice_access.router, prefix="/invoice-access", tags=["invoice-access"])
api_router.include_router(inventory.router, prefix="/inventory", tags=["inventory"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(conversion_exports.router, prefix="/conversion-exports", tags=["conversion-exports"])
api_router.include_router(parts_operations.router, prefix="/parts-operations", tags=["parts-operations"])
api_router.include_router(inventory_lifecycle.router, prefix="/parts-operations", tags=["inventory-lifecycle"])
api_router.include_router(activity.router, prefix="/activity", tags=["activity"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
api_router.include_router(labor_book_time.router, prefix="/labor-book-time", tags=["labor-book-time"])
api_router.include_router(appointments.router, prefix="/appointments", tags=["appointments"])
api_router.include_router(payments.router, prefix="/payments", tags=["payments"])
api_router.include_router(mechanics.router, prefix="/mechanics", tags=["mechanics"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(messages.router, prefix="/messages", tags=["messages"])
api_router.include_router(fleet.router, prefix="/fleet", tags=["fleet"])
api_router.include_router(driver_accountability.router, prefix="/fleet-identity", tags=["fleet-identity"])
api_router.include_router(stripe_connect.router, prefix="/stripe/connect", tags=["stripe-connect"])
api_router.include_router(stripe_webhooks.router, prefix="/webhooks/stripe", tags=["webhooks"])
api_router.include_router(quickbooks.router, prefix="/quickbooks", tags=["quickbooks"])
api_router.include_router(google_reviews.router, prefix="/google-reviews", tags=["google-reviews"])
api_router.include_router(twilio_webhooks.router, prefix="/webhooks/twilio", tags=["webhooks"])
