"""Tenant-scoped Google Business Profile reviews.

Revision ID: 106_google_reviews
Revises: 105_merge_invoice_qb_heads
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "106_google_reviews"
down_revision = "105_merge_invoice_qb_heads"
branch_labels = None
depends_on = None

def base_columns():
    return [sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True))]
def upgrade():
    op.create_table("google_business_connections", *base_columns(), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("google_account_id", sa.String(255)), sa.Column("location_id", sa.String(255)), sa.Column("location_name", sa.String(500)), sa.Column("status", sa.String(32), nullable=False, server_default="disconnected"), sa.Column("encrypted_access_token", sa.Text()), sa.Column("encrypted_refresh_token", sa.Text()), sa.Column("access_token_expires_at", sa.DateTime(timezone=True)), sa.Column("connected_at", sa.DateTime(timezone=True)), sa.Column("disconnected_at", sa.DateTime(timezone=True)), sa.Column("last_token_refresh_at", sa.DateTime(timezone=True)), sa.Column("last_token_refresh_error", sa.Text()), sa.Column("last_sync_at", sa.DateTime(timezone=True)), sa.Column("last_sync_error", sa.Text()), sa.UniqueConstraint("tenant_id"))
    op.create_table("google_business_oauth_states", *base_columns(), sa.Column("state_hash", sa.String(64), nullable=False, unique=True), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("initiated_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("consumed_at", sa.DateTime(timezone=True)))
    op.create_table("google_review_settings", *base_columns(), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("brand_voice_prompt", sa.Text(), nullable=False, server_default=""), sa.Column("reply_policy", sa.Text(), nullable=False, server_default=""), sa.Column("auto_publish_five_star", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("alert_recipients", postgresql.JSONB(), nullable=False, server_default="[]"), sa.UniqueConstraint("tenant_id"))
    op.create_table("google_reviews", *base_columns(), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("connection_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("google_business_connections.id"), nullable=False), sa.Column("google_review_id", sa.String(512), nullable=False), sa.Column("reviewer_name", sa.String(255)), sa.Column("rating", sa.Integer(), nullable=False), sa.Column("review_text", sa.Text()), sa.Column("review_created_at", sa.DateTime(timezone=True)), sa.Column("review_updated_at", sa.DateTime(timezone=True)), sa.Column("raw_payload", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("ai_draft", sa.Text()), sa.Column("ai_model", sa.String(128)), sa.Column("ai_metadata", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("reply_text", sa.Text()), sa.Column("status", sa.String(32), nullable=False, server_default="new"), sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("approved_by_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("publish_response", postgresql.JSONB()), sa.Column("publish_failure_reason", sa.Text()), sa.Column("publish_retry_count", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_publish_attempt_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("tenant_id", "google_review_id", name="uq_google_review_tenant_review"))
    op.create_table("google_review_audit_events", *base_columns(), sa.Column("tenant_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("tenants.id"), nullable=False), sa.Column("review_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("google_reviews.id")), sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("event_type", sa.String(64), nullable=False), sa.Column("metadata_json", postgresql.JSONB(), nullable=False, server_default="{}"))
    for table, cols in {"google_business_connections":["tenant_id","status"], "google_reviews":["tenant_id","status","review_created_at"], "google_review_audit_events":["tenant_id","review_id","event_type"]}.items():
        for col in cols: op.create_index(f"ix_{table}_{col}", table, [col])
def downgrade():
    op.drop_table("google_review_audit_events"); op.drop_table("google_reviews"); op.drop_table("google_review_settings"); op.drop_table("google_business_oauth_states"); op.drop_table("google_business_connections")
