"""DB-036 inventory, measurements, durable webhook inbox and company grants."""
from alembic import op

revision = "153_motive_full_scope"
down_revision = "152_motive_oauth"
branch_labels = None
depends_on = None


def upgrade():
    op.execute('ALTER TABLE motive_connections ADD COLUMN reconciliation_cutoff_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_connections ADD COLUMN last_reconciled_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_connections ADD COLUMN webhook_id UUID')
    op.execute("ALTER TABLE motive_connections ADD COLUMN webhook_generation INTEGER DEFAULT '0' NOT NULL")
    op.execute('ALTER TABLE motive_connections ADD COLUMN encrypted_webhook_secret TEXT')
    op.execute("ALTER TABLE motive_connections ADD COLUMN webhook_enabled BOOLEAN DEFAULT 'false' NOT NULL")
    op.execute('ALTER TABLE motive_connections ADD COLUMN webhook_last_received_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_connections ADD COLUMN webhook_verified_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN gateway_id VARCHAR(120)')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN gateway_identifier VARCHAR(120)')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN gateway_model VARCHAR(120)')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN provider_status VARCHAR(24)')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN metrics_received_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN faults_synced_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN metrics_observed_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN virtual_odometer_miles FLOAT')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN true_odometer_miles FLOAT')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN virtual_engine_hours FLOAT')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN true_engine_hours FLOAT')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN history_cursor_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_remote_vehicles ADD COLUMN fault_cursor_at TIMESTAMP WITH TIME ZONE')
    op.execute('ALTER TABLE motive_connections ADD CONSTRAINT uq_motive_webhook_route UNIQUE (webhook_id)')
    op.execute('ALTER TABLE motive_remote_vehicles ADD CONSTRAINT uq_motive_remote_identity UNIQUE (tenant_id, connection_id, id)')
    op.execute('CREATE TABLE motive_fleet_admin_grants (\n\ttenant_id UUID NOT NULL, \n\tfleet_customer_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\tgranted_by_user_id UUID NOT NULL, \n\trevoked_by_user_id UUID, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_motive_fleet_admin UNIQUE (tenant_id, fleet_customer_id, user_id), \n\tFOREIGN KEY(tenant_id, fleet_customer_id) REFERENCES customers (tenant_id, id), \n\tFOREIGN KEY(tenant_id) REFERENCES tenants (id), \n\tFOREIGN KEY(user_id) REFERENCES users (id), \n\tFOREIGN KEY(granted_by_user_id) REFERENCES users (id), \n\tFOREIGN KEY(revoked_by_user_id) REFERENCES users (id)\n)')
    op.execute('CREATE INDEX ix_motive_fleet_admin_grants_id ON motive_fleet_admin_grants (id)')
    op.execute('CREATE TABLE motive_history_samples (\n\ttenant_id UUID NOT NULL, \n\tconnection_id UUID NOT NULL, \n\tremote_vehicle_id UUID NOT NULL, \n\tprovider_location_id VARCHAR(120) NOT NULL, \n\tmapping_epoch TIMESTAMP WITH TIME ZONE NOT NULL, \n\tobserved_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlat FLOAT, \n\tlng FLOAT, \n\tspeed_mph FLOAT, \n\tbearing_degrees FLOAT, \n\tvirtual_odometer_miles FLOAT, \n\ttrue_odometer_miles FLOAT, \n\tvirtual_engine_hours FLOAT, \n\ttrue_engine_hours FLOAT, \n\tcontent_sha256 VARCHAR(64) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_motive_history_event UNIQUE (remote_vehicle_id, provider_location_id), \n\tFOREIGN KEY(tenant_id, connection_id, remote_vehicle_id) REFERENCES motive_remote_vehicles (tenant_id, connection_id, id)\n)')
    op.execute('CREATE INDEX ix_motive_history_observation ON motive_history_samples (remote_vehicle_id, observed_at, id)')
    op.execute('CREATE INDEX ix_motive_history_samples_id ON motive_history_samples (id)')
    op.execute('CREATE TABLE motive_faults (\n\ttenant_id UUID NOT NULL, \n\tconnection_id UUID NOT NULL, \n\tremote_vehicle_id UUID NOT NULL, \n\tprovider_fault_id VARCHAR(120) NOT NULL, \n\tmapping_epoch TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcode_label VARCHAR(120), \n\tfmi VARCHAR(40), \n\tcode VARCHAR(120), \n\tdescription VARCHAR(1000), \n\tstatus VARCHAR(16) NOT NULL, \n\tfirst_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_observed_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcontent_sha256 VARCHAR(64) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_motive_fault_event UNIQUE (connection_id, provider_fault_id), \n\tFOREIGN KEY(tenant_id, connection_id, remote_vehicle_id) REFERENCES motive_remote_vehicles (tenant_id, connection_id, id)\n)')
    op.execute('CREATE INDEX ix_motive_fault_vehicle ON motive_faults (remote_vehicle_id, last_observed_at)')
    op.execute('CREATE INDEX ix_motive_faults_id ON motive_faults (id)')
    op.execute('CREATE TABLE motive_webhook_receipts (\n\ttenant_id UUID NOT NULL, \n\tconnection_id UUID NOT NULL, \n\tconnection_generation INTEGER NOT NULL, \n\twebhook_generation INTEGER NOT NULL, \n\taction VARCHAR(48) NOT NULL, \n\tprovider_vehicle_id VARCHAR(120), \n\tprovider_object_id VARCHAR(120), \n\tpayload_sha256 VARCHAR(64) NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tprocessed_at TIMESTAMP WITH TIME ZONE, \n\tnext_attempt_at TIMESTAMP WITH TIME ZONE, \n\tattempts INTEGER NOT NULL, \n\tstatus VARCHAR(24) NOT NULL, \n\terror_code VARCHAR(48), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_motive_webhook_delivery UNIQUE (connection_id, webhook_generation, payload_sha256), \n\tFOREIGN KEY(tenant_id, connection_id) REFERENCES motive_connections (tenant_id, id)\n)')
    op.execute('CREATE INDEX ix_motive_webhook_receipts_id ON motive_webhook_receipts (id)')
    op.execute('CREATE INDEX ix_motive_inbox_pending ON motive_webhook_receipts (connection_id, status, received_at)')


def downgrade():
    op.drop_table('motive_webhook_receipts')
    op.drop_table('motive_faults')
    op.drop_table('motive_history_samples')
    op.drop_table('motive_fleet_admin_grants')
    op.drop_constraint("uq_motive_remote_identity", "motive_remote_vehicles", type_="unique")
    op.drop_constraint("uq_motive_webhook_route", "motive_connections", type_="unique")
    op.drop_column('motive_remote_vehicles', 'fault_cursor_at')
    op.drop_column('motive_remote_vehicles', 'history_cursor_at')
    op.drop_column('motive_remote_vehicles', 'true_engine_hours')
    op.drop_column('motive_remote_vehicles', 'virtual_engine_hours')
    op.drop_column('motive_remote_vehicles', 'true_odometer_miles')
    op.drop_column('motive_remote_vehicles', 'virtual_odometer_miles')
    op.drop_column('motive_remote_vehicles', 'metrics_observed_at')
    op.drop_column('motive_remote_vehicles', 'faults_synced_at')
    op.drop_column('motive_remote_vehicles', 'metrics_received_at')
    op.drop_column('motive_remote_vehicles', 'provider_status')
    op.drop_column('motive_remote_vehicles', 'gateway_model')
    op.drop_column('motive_remote_vehicles', 'gateway_identifier')
    op.drop_column('motive_remote_vehicles', 'gateway_id')
    op.drop_column('motive_connections', 'webhook_verified_at')
    op.drop_column('motive_connections', 'webhook_last_received_at')
    op.drop_column('motive_connections', 'webhook_enabled')
    op.drop_column('motive_connections', 'encrypted_webhook_secret')
    op.drop_column('motive_connections', 'webhook_generation')
    op.drop_column('motive_connections', 'webhook_id')
    op.drop_column('motive_connections', 'last_reconciled_at')
    op.drop_column('motive_connections', 'reconciliation_cutoff_at')
