"""
Default catalog data (service categories, services, inventory items) used for
tenant preload via API endpoints and the preload_catalog.py CLI script.
"""
from decimal import Decimal

DEFAULT_CATEGORIES = [
    {"name": "PM Services",    "description": "Preventive maintenance to keep your fleet running", "icon": "🔧", "sort_order": 1, "is_pm": True},
    {"name": "Brakes",         "description": "Brake services and repairs",                        "icon": "🛑", "sort_order": 2},
    {"name": "Inspections",    "description": "Safety and compliance inspections",                 "icon": "📋", "sort_order": 3},
    {"name": "Tires",          "description": "Tire services and replacements",                   "icon": "🛞", "sort_order": 4},
    {"name": "Electrical",     "description": "Batteries, starters, alternators, and electrical systems", "icon": "🔋", "sort_order": 5},
    {"name": "Other Services", "description": "Additional truck services",                        "icon": "🛠️", "sort_order": 6},
]

DEFAULT_SERVICES = [
    # PM Services
    {"category": "PM Services",    "name": "PM Service - Level A",           "description": "Basic preventive maintenance: oil change, filter replacement, fluid check, and 23-point inspection.",                 "duration_minutes": 60,  "base_price": Decimal("249.00"),  "icon": "🛢️", "sort_order": 1},
    {"category": "PM Services",    "name": "PM Service - Level B",           "description": "Comprehensive PM: oil change, all filters, fluid top-off, greasing, and 50-point inspection.",                        "duration_minutes": 120, "base_price": Decimal("449.00"),  "icon": "⚙️", "sort_order": 2},
    {"category": "PM Services",    "name": "PM Service - Level C",           "description": "Full service PM: includes Level B plus transmission service, coolant check, and brake adjustment.",                   "duration_minutes": 180, "base_price": Decimal("699.00"),  "icon": "🔩", "sort_order": 3},
    {"category": "PM Services",    "name": "Oil Change Only",                "description": "Quick oil and filter change with synthetic diesel oil.",                                                               "duration_minutes": 45,  "base_price": Decimal("189.00"),  "icon": "🛢️", "sort_order": 4},
    # Brakes
    {"category": "Brakes",         "name": "Brake Inspection",               "description": "Complete brake system inspection with detailed condition report.",                                                     "duration_minutes": 30,  "base_price": Decimal("59.00"),   "icon": "🔍", "sort_order": 1},
    {"category": "Brakes",         "name": "Brake Pad Replacement - Per Axle", "description": "Replace brake pads on one axle. Includes inspection and adjustment.",                                             "duration_minutes": 90,  "base_price": Decimal("349.00"),  "icon": "🛑", "sort_order": 2},
    {"category": "Brakes",         "name": "Full Brake Job - All Axles",     "description": "Complete brake service: pads, drums/rotors inspection, adjustment on all axles.",                                     "duration_minutes": 240, "base_price": Decimal("1299.00"), "icon": "🔴", "sort_order": 3},
    {"category": "Brakes",         "name": "Brake Adjustment",               "description": "Adjust and set brake slack adjusters for optimal performance.",                                                       "duration_minutes": 45,  "base_price": Decimal("89.00"),   "icon": "🔧", "sort_order": 4},
    # Inspections
    {"category": "Inspections",    "name": "DOT Annual Inspection",          "description": "Complete DOT annual inspection and certification. Required for compliance.",                                           "duration_minutes": 90,  "base_price": Decimal("149.00"),  "icon": "✅", "sort_order": 1},
    {"category": "Inspections",    "name": "Monthly Safety Inspection",      "description": "Comprehensive monthly inspection covering all major systems and safety equipment.",                                   "duration_minutes": 60,  "base_price": Decimal("99.00"),   "icon": "📅", "sort_order": 2},
    {"category": "Inspections",    "name": "Weekly Safety Check",            "description": "Quick weekly safety inspection: lights, tires, brakes, fluids, and walk-around.",                                    "duration_minutes": 30,  "base_price": Decimal("49.00"),   "icon": "📋", "sort_order": 3},
    {"category": "Inspections",    "name": "Pre-Trip Inspection",            "description": "Detailed pre-trip inspection before long hauls. Peace of mind on the road.",                                         "duration_minutes": 45,  "base_price": Decimal("79.00"),   "icon": "🚛", "sort_order": 4},
    # Tires
    {"category": "Tires",          "name": "Tire Change - Single",           "description": "Mount and balance one new tire. Disposal of old tire included.",                                                      "duration_minutes": 30,  "base_price": Decimal("45.00"),   "icon": "🛞", "sort_order": 1},
    {"category": "Tires",          "name": "Tire Change - Per Axle",         "description": "Mount and balance tires on one axle (2 or 4 tires). Disposal included.",                                             "duration_minutes": 60,  "base_price": Decimal("120.00"),  "icon": "🔄", "sort_order": 2},
    {"category": "Tires",          "name": "Tire Rotation",                  "description": "Rotate tires for even wear and extended life.",                                                                       "duration_minutes": 45,  "base_price": Decimal("79.00"),   "icon": "🔃", "sort_order": 3},
    {"category": "Tires",          "name": "Tire Repair - Patch/Plug",       "description": "Professional tire repair. Assessment to determine if repair is safe.",                                               "duration_minutes": 30,  "base_price": Decimal("35.00"),   "icon": "🔧", "sort_order": 4},
    {"category": "Tires",          "name": "Wheel Alignment",                "description": "Full wheel alignment check and adjustment for all axles.",                                                            "duration_minutes": 90,  "base_price": Decimal("249.00"),  "icon": "📐", "sort_order": 5},
    # Other Services
    # Electrical
    {"category": "Electrical",     "name": "Battery Test & Replacement",     "description": "Load test batteries and replace if needed. Includes terminal cleaning.",                                             "duration_minutes": 60,  "base_price": Decimal("100.00"),  "icon": "🔋", "sort_order": 1},
    {"category": "Electrical",     "name": "Alternator Replacement",         "description": "Diagnose charging system, remove and replace alternator, verify output.",                                            "duration_minutes": 120, "base_price": Decimal("200.00"),  "icon": "⚡", "sort_order": 2},
    {"category": "Electrical",     "name": "Starter Replacement",            "description": "Remove and replace starter motor. Includes cable inspection and testing.",                                           "duration_minutes": 120, "base_price": Decimal("200.00"),  "icon": "🔌", "sort_order": 3},
    {"category": "Electrical",     "name": "Headlight Bulb Replacement",     "description": "Replace headlight bulb(s). Includes aim check.",                                                                      "duration_minutes": 30,  "base_price": Decimal("50.00"),   "icon": "💡", "sort_order": 4},
    # Other Services
    {"category": "Other Services", "name": "Diagnostic Scan",                "description": "Computer diagnostic for check engine lights, fault codes, and system analysis.",                                     "duration_minutes": 30,  "base_price": Decimal("99.00"),   "icon": "💻", "sort_order": 1},
    {"category": "Other Services", "name": "A/C Service",                    "description": "A/C system inspection, leak check, and refrigerant recharge.",                                                       "duration_minutes": 60,  "base_price": Decimal("179.00"),  "icon": "❄️", "sort_order": 2},
    {"category": "Other Services", "name": "DEF System Service",             "description": "DEF system inspection, fluid top-off, and filter replacement.",                                                      "duration_minutes": 45,  "base_price": Decimal("129.00"),  "icon": "💧", "sort_order": 3},
    {"category": "Other Services", "name": "DPF Cleaning",                   "description": "Diesel Particulate Filter cleaning and regeneration service.",                                                       "duration_minutes": 120, "base_price": Decimal("399.00"),  "icon": "🌫️", "sort_order": 4},
]

DEFAULT_INVENTORY = [
    {"sku": "BRK-PAD-001",   "name": "Heavy Duty Brake Pads - Front",    "description": "Premium ceramic brake pads for semi-trucks",         "category": "Brakes",        "stock_quantity": 24, "reorder_level": 10, "cost": Decimal("85.00"),   "selling_price": Decimal("145.00"), "supplier_name": "FleetParts Pro",      "supplier_contact": "1-800-555-0101"},
    {"sku": "BRK-PAD-002",   "name": "Heavy Duty Brake Pads - Rear",     "description": "Premium ceramic brake pads for semi-trucks",         "category": "Brakes",        "stock_quantity": 18, "reorder_level": 10, "cost": Decimal("95.00"),   "selling_price": Decimal("165.00"), "supplier_name": "FleetParts Pro",      "supplier_contact": "1-800-555-0101"},
    {"sku": "BRK-ROTOR-001", "name": "Brake Rotor - 15 inch",            "description": "Heavy duty vented brake rotor",                      "category": "Brakes",        "stock_quantity": 8,  "reorder_level": 4,  "cost": Decimal("220.00"),  "selling_price": Decimal("350.00"), "supplier_name": "FleetParts Pro",      "supplier_contact": "1-800-555-0101"},
    {"sku": "OIL-15W40-5G",  "name": "Diesel Engine Oil 15W-40 (5 Gal)", "description": "Full synthetic diesel engine oil",                   "category": "Fluids",        "stock_quantity": 12, "reorder_level": 5,  "cost": Decimal("75.00"),   "selling_price": Decimal("120.00"), "unit_type": "gallon", "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "OIL-FLT-001",   "name": "Oil Filter - Cummins ISX",         "description": "OEM spec oil filter for Cummins ISX engines",        "category": "Filters",       "stock_quantity": 35, "reorder_level": 15, "cost": Decimal("18.00"),   "selling_price": Decimal("35.00"),  "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "AIR-FLT-001",   "name": "Air Filter - Primary",             "description": "Heavy duty primary air filter",                      "category": "Filters",       "stock_quantity": 20, "reorder_level": 8,  "cost": Decimal("45.00"),   "selling_price": Decimal("85.00"),  "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "AIR-FLT-002",   "name": "Air Filter - Secondary",           "description": "Heavy duty secondary/safety air filter",             "category": "Filters",       "stock_quantity": 15, "reorder_level": 8,  "cost": Decimal("25.00"),   "selling_price": Decimal("55.00"),  "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "FUEL-FLT-001",  "name": "Fuel Filter Kit",                  "description": "Primary and secondary fuel filter set",              "category": "Filters",       "stock_quantity": 3,  "reorder_level": 6,  "cost": Decimal("65.00"),   "selling_price": Decimal("110.00"), "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "BELT-SERP-001", "name": "Serpentine Belt - 10 Rib",         "description": "Heavy duty serpentine belt",                         "category": "Belts & Hoses", "stock_quantity": 6,  "reorder_level": 4,  "cost": Decimal("55.00"),   "selling_price": Decimal("95.00"),  "supplier_name": "FleetParts Pro",      "supplier_contact": "1-800-555-0101"},
    {"sku": "COOL-ANT-5G",   "name": "Extended Life Coolant (5 Gal)",    "description": "Heavy duty extended life antifreeze/coolant",        "category": "Fluids",        "stock_quantity": 8,  "reorder_level": 4,  "cost": Decimal("45.00"),   "selling_price": Decimal("75.00"),  "unit_type": "gallon", "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "TURBO-ACT-001", "name": "Turbo Actuator",                   "description": "Variable geometry turbo actuator",                   "category": "Engine",        "stock_quantity": 2,  "reorder_level": 2,  "cost": Decimal("450.00"),  "selling_price": Decimal("750.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "DPF-FLTR-001",  "name": "DPF Filter Assembly",              "description": "Diesel particulate filter - remanufactured",         "category": "Exhaust",       "stock_quantity": 1,  "reorder_level": 1,  "cost": Decimal("1800.00"), "selling_price": Decimal("2800.00"),"supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "BATT-HD-001",   "name": "Heavy Duty Battery - Group 31",    "description": "1000 CCA commercial truck battery",                  "category": "Electrical",    "stock_quantity": 4,  "reorder_level": 2,  "cost": Decimal("180.00"),  "selling_price": Decimal("280.00"), "supplier_name": "Battery Warehouse",   "supplier_contact": "1-800-555-0404"},
    {"sku": "STRTR-001",     "name": "Starter Motor - Delco 39MT",       "description": "Remanufactured heavy duty starter",                  "category": "Electrical",    "stock_quantity": 0,  "reorder_level": 1,  "cost": Decimal("350.00"),  "selling_price": Decimal("550.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "ALT-001",       "name": "Alternator - 160 Amp",             "description": "Heavy duty alternator for commercial trucks",         "category": "Electrical",    "stock_quantity": 2,  "reorder_level": 1,  "cost": Decimal("280.00"),  "selling_price": Decimal("450.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "TRANS-FLT-001", "name": "Transmission Filter Kit",          "description": "Automatic transmission filter and gasket kit",       "category": "Filters",       "stock_quantity": 10, "reorder_level": 4,  "cost": Decimal("42.00"),   "selling_price": Decimal("78.00"),  "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "TRANS-FL-1G",   "name": "Transmission Fluid (1 Gal)",       "description": "Allison TES-295 approved transmission fluid",        "category": "Fluids",        "stock_quantity": 20, "reorder_level": 8,  "cost": Decimal("22.00"),   "selling_price": Decimal("38.00"),  "unit_type": "gallon", "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "DEF-2.5G",      "name": "Diesel Exhaust Fluid (2.5 Gal)",   "description": "ISO 22241 compliant DEF for SCR systems",            "category": "Fluids",        "stock_quantity": 30, "reorder_level": 10, "cost": Decimal("12.00"),   "selling_price": Decimal("22.00"),  "unit_type": "gallon", "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "BRKFL-001",     "name": "Brake Fluid DOT 3 (32 oz)",        "description": "Heavy duty DOT 3 brake fluid",                       "category": "Fluids",        "stock_quantity": 12, "reorder_level": 6,  "cost": Decimal("8.00"),    "selling_price": Decimal("16.00"),  "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "EGR-VLV-001",   "name": "EGR Valve",                        "description": "Exhaust gas recirculation valve - OEM replacement",  "category": "Engine",        "stock_quantity": 2,  "reorder_level": 1,  "cost": Decimal("380.00"),  "selling_price": Decimal("620.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "INJECTER-001",  "name": "Fuel Injector",                    "description": "Remanufactured common rail fuel injector",            "category": "Engine",        "stock_quantity": 4,  "reorder_level": 2,  "cost": Decimal("280.00"),  "selling_price": Decimal("450.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "HVAC-COMP-001", "name": "A/C Compressor",                   "description": "Remanufactured A/C compressor for heavy trucks",      "category": "HVAC",          "stock_quantity": 1,  "reorder_level": 1,  "cost": Decimal("520.00"),  "selling_price": Decimal("850.00"), "supplier_name": "Diesel Parts Direct", "supplier_contact": "1-800-555-0303"},
    {"sku": "REFRIG-134A",   "name": "Refrigerant R-134a (30 lb)",       "description": "A/C refrigerant for truck cab systems",              "category": "HVAC",          "stock_quantity": 3,  "reorder_level": 2,  "cost": Decimal("95.00"),   "selling_price": Decimal("165.00"), "supplier_name": "TruckLube Supply",    "supplier_contact": "1-800-555-0202"},
    {"sku": "WIPER-24",      "name": "Wiper Blade - 24 inch",            "description": "Heavy duty commercial wiper blade",                  "category": "Accessories",   "stock_quantity": 16, "reorder_level": 6,  "cost": Decimal("14.00"),   "selling_price": Decimal("25.00"),  "supplier_name": "FleetParts Pro",      "supplier_contact": "1-800-555-0101"},
    {"sku": "LIGHTBULB-55W", "name": "Headlight Bulb - 55W H7",          "description": "OEM replacement headlight bulb",                     "category": "Electrical",    "stock_quantity": 20, "reorder_level": 8,  "cost": Decimal("12.00"),   "selling_price": Decimal("22.00"),  "supplier_name": "Battery Warehouse",   "supplier_contact": "1-800-555-0404"},
]
